#!/bin/bash

#
# Copyright (C) 2018-2020 Sebastian Kuzminsky
# 
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License along
# with this program; if not, write to the Free Software Foundation, Inc.,
# 51 Franklin Street, Fifth Floor, Boston, MA 02110-1301 USA.
# 

if [[ $# -gt 0 ]]; then
    TEST_DIRS="$@"
else
    TEST_DIRS=$PWD
fi

NUM_TESTS=$(find ${TEST_DIRS} -name 'test*.py' -o -name 'test.sh' -o -name 'test.s2g' | wc -l)
echo ${NUM_TESTS} " tests to check"

rm -f log/failed_tests.log
rm -f log/skipped_tests.log
rm -f log/ok_tests.log

/usr/bin/parallel -j+0  ./run_one_test '{}' ::: $(find ${TEST_DIRS} -name 'test*.py' -o -name 'test.sh' -o -name 'test.s2g')
