#!/bin/bash

export PYTHONPATH=$(dirname $(realpath $0))/..:${PYTHONPATH}
export PATH=$(dirname $(realpath $0))/..:${PATH}

do_test() {
    TEST_FILE=$(basename "$1")
    rm -f stderr
    if [ -f expected.ngc ]; then
        if [[ "${TEST_FILE}" =~ .s2g$ ]]; then
            svg2gcode --job ${TEST_FILE} test.svg >| result.ngc 2>> stderr
        else
            ./${TEST_FILE} > result.ngc 2>> stderr
        fi
    else
        ./${TEST_FILE} 2>> stderr
    fi
    if [ $? -ne 0 ]; then
        echo "FAILED: non-zero exit code"
        return 1
    fi

    if [ -f expected.ngc ]; then
        diff -u expected.ngc result.ngc
        if [ $? -ne 0 ]; then
            echo "FAILED: unexpected G-code result"
            return 1
        fi
    fi

    if [ -f expected.canon ]; then
        rs274 -t /dev/null -v /dev/null -g result.ngc >| result.canon 2>> stderr
        diff -u expected.canon result.canon
        if [ $? -ne 0 ]; then
            echo "FAILED: unexpected Canon result"
            return 1
        fi
    fi

    return 0
}


if [[ $# -gt 0 ]]; then
    TEST_DIRS="$@"
else
    TEST_DIRS=$PWD
fi

FAILED=""
for TEST in $(find ${TEST_DIRS} -name 'test.py' -o -name 'test.sh' -o -name 'test.s2g' | sort); do
    TEST_DIR=$(dirname ${TEST})
    TEST_NAME=$(realpath --relative-to=${PWD}/.. ${TEST_DIR})
    ORIG_DIR=${PWD}

    echo "running ${TEST_NAME}"
    cd ${TEST_DIR}
    do_test ${TEST}
    if [ $? -ne 0 ]; then
        FAILED="${FAILED} ${TEST_NAME}"
    else
        rm -f result.ngc
        rm -f result.canon
        rm -f stderr
    fi
    cd ${ORIG_DIR}
done


if [ -n "${FAILED}" ]; then
    echo "failed tests:"
    for TEST in ${FAILED}; do
        echo "    ${TEST}"
    done
    exit 1
fi

echo "all tests passed!"
exit 0
