= svg2gcode(1)


== NAME

svg2gcode - produce g-code tool paths from SVG files


== SYNOPSIS

*svg2gcode* [_OPTIONS_] --job JOBFILE FILE.SVG


== DESCRIPTION

svg2gcode reads a job description file and an SVG file (containing a
single closed path), and produces the corresponding g-code.


== OPTIONS

*-s*, *--speed* _N_::

    The spindle speed to use, in RPM.  (Default: 1000)

*-f*, *--feed* _N_::

    The tool feed rate to use, in mm/minute.  (Default: 1000)

*--z-traverse* _N_::

    The Z level for safe traverses above the work and workholding, in mm.
    (Default: 10)

*--z-top-of-material* _N_::

    The Z level where the material starts, in mm.  (Default: 0)

*--z-cut-depth* _N_::

    The Z level to cut down to, in mm.  (Default: 0)


== Job File Format

The job file is a json document.

At the top level there's a hash with a key named "jobs", whose value
is a list of job descriptions.  svg2gcode writes g-code for each job
description in the list.

Each job description is a hash, and has a key named "job-type" whose
value is the type of the job.  The supported job types and their arguments
(provided as additional key/value pairs in the job description hash) are:


=== Job type: engrave

The toolpath follows the path in the SVG.

No arguments.

Example:

    {
	"jobs": [
	    {
		"job-type": "engrave"
	    }
	]
    }


=== Job type: offset

The toolpath is offset inwards or outwards from the path in the SVG.

Arguments:

*distance* (float):: Distance from the input path to the tool path.
Positive distances are in the interior of the SVG path, negative distances
are on the outside of the SVG path.

Example:

    {
	"jobs": [
	    {
		"job-type": "offset",
		"distance": 2.1
	    }
	]
    }


=== Job type: pocket2

Make a pocket from the SVG path.

svg2gcode uses the SVG path (optionally offset by a finishing allowance
argument) as the material contour of the wall of the pocket,

It cuts a slot around the inside of this adjustted material contour.

The slot leaves zero or more "islands" of remaining material in the
pocket.

svg2gcode removes the islands one by one using the side of the endmill
to shrink the island from the edges.  Each pass removes width-of-cut
material from the perimeter of the island until nothing remains, then
moves on to the next island.

svg2gcode tries to keep the tool down in the pocket as much as it can,
but some of the transitions between passes trigger defensive "raise,
traverse, plunge" movements.

Arguments:

*tool-diameter* (float):: Diameter of the end mill used, in mm.

*width-of-cut* (float):: Desired width-of-cut when shoulder milling,
in mm.

*finishing-allowance* (float):: Make the pocket smaller than the SVG
path by this amount, in mm.

Example:

    {
	"jobs": [
	    {
		"job-type": "pocket2",
		"tool-diameter": 15.25,
		"width-of-cut": 5.125,
		"finishing-allowance": 5.0
	    }
	]
    }


=== Job type: pocket

Old simple pocketing algorithm.  Obsolete, use pocket2 instead.
