= svg2gcode(1)


== NAME

svg2gcode - produce g-code tool paths from SVG files


== SYNOPSIS

*svg2gcode* [_OPTIONS_] JOBFILE FILE.SVG


== DESCRIPTION

svg2gcode reads a job description file and an SVG file (containing one
or more closed paths), and produces the corresponding g-code.


== OPTIONS

*--debug*::
Print extra debugging info to stderr.  Useful for submitting bug reports.

*-s*, *--speed* _N_::
The spindle speed to use, in RPM.  (Default: 1000 rpm)

*-f*, *--feed* _N_::
The tool feed rate to use, in mm/minute.  Used by the 'engrave' and
'offset' job types.  (Default: 100.0 mm/min)

 *--shoulder-feed* _N_::
The tool feed rate to use for shoulder milling, in mm/minute.  Used by
the 'pocket' operation.  (Default: 90.0 mm/min)

*--slot-feed* _N_::
The tool feed rate to use for slot milling, in mm/minute.  Used by the
'pocket' operation.  (Default: 75.0 mm/min)

*--plunge-feed* _N_::
The tool feed rate to use for plunging cuts, in mm/minute.  Used by all
job types.  (Default: 50.0 mm/min)

*--z-traverse* _N_::
The Z level for safe traverses above the work and workholding, in mm.
(Default: 10)

*--z-approach* _N_::
The Z level down to which we should rapid, before slowing to the
feed rate to approach the work, in mm.  (Default: 0.5 mm above
`--z-top-of-material`).

*--z-top-of-material* _N_::
The Z level where the material starts, in mm.  (Default: 0)

*--z-cut-depth* _N_::
The Z level to cut down to, in mm.  Must be lower than
*--z-top-of-material*.  (Default: -1)

*--path* _N_::
Operate on the Nth path from the input SVG file.  May be specified
multiple times to operate on multiple paths.  The path(s) specified using
--path override any paths specified in the job file.  If no --path is
specified and no paths are specified in the job file, operate on *all*
paths from the input SVG file.

*--gcode-orgin* _{viewbox-lower-left, svg-origin}_::
There are two places in the input SVG that can serve as a reasonable
point for the gcode origin: 'viewbox-lower-left' and 'svg-origin'.
+
The SVG native coordinate system has its origin in the upper left corner,
but humans are often accustomed to having the origin in the lower left
corner (what SVG calls the "viewbox lower left" corner).
+
By default svg2gcode translates the input SVG paths so that the viewbox
(ie what you see in an SVG viewer or editor) appears in the positive X,
positive Y quadrant of the G-code coordinate space, with the lower left
corner of the viewbox at the origin of the G-code coordinate space.
This is generally what you want if you're working with a single SVG.
+
However, if you have multiple related SVGs containing different aspect
of the same part/model, then the viewboxes might be out of alignment,
and the paths from the different SVGs won't line up.  In this situation
you can disable the viewbox-based translation by setting the G-code
coordinate system origin equal to the SVG coordinate system origin.
+
(Default: viewbox-lower-left)


== Job File Format

The job file is a json document.

At the top level there's an object with a single property named "jobs",
whose value is an array of job descriptions.

Each job description is an object with two properties, named "paths"
and "operations".

"paths" is an array of path indexes (can be overridden using the
command-line argument --path, see above).  If the "paths" array is
empty and no --path argument is given, operate on all paths in the input
SVG file.

"operations" is an array of operation descriptions, as enumerated below.


=== Operation: engrave

The toolpath follows the path in the SVG.

Arguments:

*ramp-slope* (float, optional):: If specified, `ramp-slope` enables
ramp entry into the cut.  The value is the Z depth per unit horizontal
distance of the ramp entry move.  `ramp-slope` also enables a move at
the end of the path to remove the entry ramp.  The ramp entry move may
wrap around the path.  If `ramp-slope` is not specified it uses a full
depth plunge entry.

Examples:

    {
        "jobs": [
            {
                "paths": [ 0 ],
                "operations": [
                    {
                        "engrave": { }
                    }
                ]
            },
            {
                "paths": [ 1, 2 ],
                "operations": [
                    {
                        "engrave": {
                            "ramp-slope": 0.1
                        }
                    }
                ]
            }
        ]
    }


=== Operation: offset

The toolpath is offset inwards or outwards from the path in the SVG.

Arguments:

*distance* (float):: Distance from the input path to the tool path.
Positive distances are in the interior of the SVG path, negative distances
are on the outside of the SVG path.

*max-depth-of-cut* (float, optional):: Maximum depth of a milling pass,
in mm.  Defaults to `(--z-top-of-material - --z-cut-depth)` so it cuts
in a single pass.

*ramp-slope* (float, optional):: If specified, `ramp-slope` enables
ramp entry into the cut.  The value is the Z depth per unit horizontal
distance of the ramp entry move.  `ramp-slope` also enables a move at
the end of the path to remove the entry ramp.  The ramp entry move may
wrap around the path.  If `ramp-slope` is not specified it uses a full
depth plunge entry.

*work-holding-tabs* (json object, optional):: If specified, add
work-holding tabs to the offset path.  The number, width, and height
of the work-holding tabs can be specified by key/value pairs in the
`work-holding-tabs` object (see the `Work-holding tabs` section below).

Example:

    {
        "jobs": [
            {
                "paths": [ 0, 1 ],
                "operations: [
                    {
                        "offset": {
                            "distance": 2.1
                        }
                    },
                    {
                        "offset": {
                            "distance": 1.0,
                            "max-depth-of-cut": 3.1,
                            "ramp-slope": 0.05,
                            "work-holding-tabs": {
                                "number-of-tabs": 4,
                                "height": 1.5,
                                "width": 12.5
                            }
                        }
                    }
                ]
            }
        ]
    }


=== Operation: pocket

Make a pocket from the SVG path.

svg2gcode uses the SVG path (optionally offset inwards by a finishing
allowance argument) as the material contour of the wall of the pocket.

It cuts a slot around the inside of this adjusted material contour
(using either plunge or ramped entry).

The slot leaves zero or more "islands" of remaining material in the
pocket.

svg2gcode removes the islands one by one using shoulder milling to
shrink the island from the edges.  Each pass removes `width-of-cut`
material from the perimeter of the island until nothing remains, then
it moves on to the next island.  Each pass begins with a plunge entry.

Arguments:

*tool-diameter* (float):: Diameter of the end mill used, in mm.

*width-of-cut* (float):: Desired radial width-of-cut when shoulder
milling, in mm.

*finishing-allowance* (float, optional):: Make the pocket smaller than
the SVG path by this amount, in mm.  Defaults to 0 mm if omitted.

*slot-max-depth-of-cut* (float, optional):: Maximum axial depth of a slot
milling pass, in mm.  Defaults to `(--z-top-of-material - --z-cut-depth)`
so it cuts the pocket in a single pass.

*shoulder-max-depth-of-cut* (float, optional):: Maximum depth of a
shoulder milling pass, in mm.  Defaults to `(--z-top-of-material -
--z-cut-depth)` so it cuts the pocket in a single pass.

*ramp-slope* (float, optional):: If specified, *ramp-slope* enables
ramp entry into the slotting cuts.  The value is the Z depth per unit
horizontal distance of the ramp entry move.  *ramp-slope* also enables a
move at the end of the slotting path to remove the entry ramp.  The ramp
entry move may wrap around the path.  If *ramp-slope* is not specified
it uses a full depth plunge entry.

Example:

    {
        "jobs": [
            {
                "paths": [ 0 ],
                "operations": [
                    {
                        "pocket": {
                            "tool-diameter": 15.25,
                            "width-of-cut": 5.125
                        }
                    }
                ]
            },
            {
                "paths": [ 1 ],
                "operations": [
                    {
                        "pocket": {
                            "tool-diameter": 15.25,
                            "width-of-cut": 5.125,
                            "finishing-allowance": 5.0,
                            "slot-max-depth-of-cut": 1.2,
                            "shoulder-max-depth-of-cut": 2.8,
                            "ramp-slope": 0.1
                        }
                    }
                ]
            }
        ]
    }


=== Operation: drill

Drill at the center of a circular path.  The input path must consist
of two Arc segments that make up one complete circle.  The output will
be a drilling operation (G81) at the center of the circle.  The plunge
feed rate will be used.

This job type takes no arguments.

Example:

    {
        "jobs": [
            {
                "paths": [ 0, 1, 2 ],
                "operations": [
                    {
                        "drill": { }
                    }
                ]
            }
        ]
    }


=== Operation: translate

The `translate` operation moves the output gcode of its child operation(s)
by a specified amount in X and Y.

Arguments:

*operations* (list of objects):: The list of operations to translate.
The list can hold any operations except `duplicate` and `translate`.

*x* (float, optional):: Distance to translate the operations in X.
Defaults to 0.0 if omitted.

*y* (float, optional):: Distance to translate the operations in Y.
Defaults to 0.0 if omitted.

Example:

    {
        "jobs": [
            {
                "paths": [ 0, 1 ],
                "operations": [
                    {
                        "translate": {
                            "x": 15.0,
                            "y": -100,
                            "operations": [
                                ...
                            ]
                        }
                    }
                ]
            }
        ]
    }


=== Operation: duplicate

The `duplicate` operation makes several copies of the output gcode of its child operation(s)
in a regular X/Y grid.

Arguments:

*operations* (list of objects):: The list of operations to duplicate.
The list can hold any operations except `duplicate` and `translate`.

*x-offset* (float, optional):: X distance between adjacent to copies in
the grid.  Defaults to 0.0 if omitted, which is not useful.

*y-offset* (float, optional):: Y distance between adjacent to copies in
the grid.  Defaults to 0.0 if omitted, which is not useful.

*x-count* (float, optional):: Number of duplicate copies in the X
direction.  Defaults to 1 if omitted.

*y-count* (float, optional):: Number of duplicate copies in the Y
direction.  Defaults to 1 if omitted.

Example:

    {
        "jobs": [
            {
                "paths": [ 0, 1 ],
                "operations": [
                    {
                        "duplicate": {
                            "x-offset": 15.0,
                            "y-offset": -100,
                            "x-count": 5,
                            "y-count": 10,
                            "operations": [
                                ...
                            ]
                        }
                    }
                ]
            }
        ]
    }


=== Work-holding tabs

Properties in the `work-holding-tabs` object of the `offset` operation
are:

*number-of-tabs* (integer, required):: Add this number of work-holding
tabs.

*height* (float, optional):: Height of work holding tabs, in mm.
Defaults to 0.5mm if omitted.

*width* (float, optional):: Width of work holding tabs, in mm.  No cutter
diameter compensation is performed when "stepping over" the tabs, so
this value should be greater than one cutter diameter or the tabs will
be cut away.  Defaults to 10mm if omitted.

*locations* (list of float, optional):: This is a list of locations along
the path where the tabs should start.  If specified, the length of the
list must be the same as `number-of-tabs`.  If the `locations` list is not
specified, the tabs will be automatically placed evenly around the path.


== Old jobfile format (obsolete)

An older jobfile format is still accepted, but no longer recommended
or documented.  Use the new jobfile format described above.
